### ISSUE TITLE
Doesn't connect interfaces automatically

### ISSUE THREAD

**Issue by kenvandine** [snapcore/snapd-desktop-integration#10]
With rev 10 and snapd rev 15447 from edge, it doesn't automatically connect the greedy plugs

**Comment by jhenstridge** [comment]
Ken mentioned the gtk-theme-yaru-mate and gtk-theme-pocillo snaps as problems. It doesn't look like either of them have a snap declaration to allow auto connect or greedy plugs:

```
$ snap known --remote snap-declaration series=16 snap-id=IdqpXws6k4Rf2238X9Fi294b8HXGREXz
type: snap-declaration
authority-id: canonical
series: 16
snap-id: IdqpXws6k4Rf2238X9Fi294b8HXGREXz
publisher-id: nyjFDUxZVxBIve0nuIPbU6uWOh8ZvrEE
snap-name: gtk-theme-yaru-mate
timestamp: 2021-03-31T19:03:54.357669Z
sign-key-sha3-384: BWDEoaqyr25nF5SNCvEv2v7QnM9QsfCc0PBMYD_i2NGSQ32EF2d4D0hqUel3m8ul
...
```

```
$ snap known --remote snap-declaration series=16 snap-id=sg77DMY50LWlDJkQ9DKtJburFwYzti0n
type: snap-declaration
authority-id: canonical
series: 16
snap-id: sg77DMY50LWlDJkQ9DKtJburFwYzti0n
publisher-id: t8QcP6ncup3o5o2J2jQexFJlv2n7Y3VI
snap-name: gtk-theme-pocillo
timestamp: 2020-06-08T21:05:20.681679Z
sign-key-sha3-384: BWDEoaqyr25nF5SNCvEv2v7QnM9QsfCc0PBMYD_i2NGSQ32EF2d4D0hqUel3m8ul
...
```

Compare this with gtk-theme-traditionalhumanized:

```
$ snap known --remote snap-declaration series=16 snap-id=JcEieEaWssvHBXLhtEvh0mdo9Q6Utoss
type: snap-declaration
format: 2
authority-id: canonical
revision: 1
series: 16
snap-id: JcEieEaWssvHBXLhtEvh0mdo9Q6Utoss
publisher-id: EH9A6Xg1QtCjYt4v3QlBVTPLAHDvEIn6
slots:
  content:
    allow-auto-connection:
      -
        plug-attributes:
          content: $SLOT(content)
        slot-attributes:
          content: gtk-3-themes
        slots-per-plug: *
      -
        plug-attributes:
          content: $SLOT(content)
        slot-attributes:
          content: gtk-2-themes
        slots-per-plug: *
snap-name: gtk-theme-traditionalhumanized
timestamp: 2020-09-08T21:58:40.222991Z
sign-key-sha3-384: BWDEoaqyr25nF5SNCvEv2v7QnM9QsfCc0PBMYD_i2NGSQ32EF2d4D0hqUel3m8ul
...
```

These other snaps would need to request a similar snap declaration in the store for auto-connection to occur. For reference, here is the request I made for gtk-common-themes and gtk-theme-traditionalhumanized:

https://forum.snapcraft.io/t/auto-connect-and-greedy-plug-behaviour-for-for-gtk-common-themes-and-gtk-theme-traditionalhumanized-snaps/19113?u=jamesh

**Comment by jhenstridge** [comment]
Martin has requested the store assertion for the Ubuntu MATE theme snaps here:

https://forum.snapcraft.io/t/auto-connect-and-greedy-plug-behaviour-for-gtk-theme-yaru-mate-and-icon-theme-yaru-mate/29443

**Comment by jhenstridge** [comment]
And the request for the Pocillo theme:

https://forum.snapcraft.io/t/auto-connect-and-greedy-plug-behaviour-for-gtk-theme-pocillo/29444
