### ISSUE TITLE
snap theme notification does nothing

### ISSUE THREAD

**Issue by hellsworth** [snapcore/snapd-desktop-integration#13]
On a fresh and updated 22.04 system, if a user installs a local theme and selects it in gnome-tweaks ("Legacy Applications"="Orchis") then snapd-desktop-integration prompts the user to install the equivalent theme from the snap store (if it exists).

![Screenshot from 2022-06-22 13-35-22](https://user-images.githubusercontent.com/12970280/175385405-59ab4506-fc94-4d88-9113-abfb45718425.png)

If the user doesn't see this notification in a few seconds and take action, then the window goes away and a there is a notification found in the list (click the date to see the notifications list).

Then if the user clicks that notification, it goes away and does nothing. Then there is no easy way for the user to re-engage this action to install the appropriate theme.

I expect that when I click this notification, it should prompt the user just like it did initially. There should be a pop up box with the same text that was originally displayed, with yes and no buttons.

**Comment by kenvandine** [comment]
I guess the notification that persists doesn't have the actions embedded.  We should check the API to see if we're not using it correctly.

**Comment by hellsworth** [comment]
Similarly, when you do catch the notification and say "Yes" and then it fails for some reason, the error message just says Failed with no reason and when you click the Failed notification, it does nothing.

![Screenshot from 2022-06-28 15-30-59](https://user-images.githubusercontent.com/12970280/176302209-b9ae206f-8819-4352-b601-67bec5ca62ce.png)

**Comment by jhenstridge** [comment]
I think the issue with missed notifications is that gnome-shell removes the actions when transferring them to the tray, and will only send through the "default" action. Our actions are called "yes" and "no", so libnotify never fires our action callback. It might be enough to rename the "yes" action to "default". I'll need to check what that does to the UI though.

For the "Failed." notification bubble, we're currently only showing the error message on stdout:

https://github.com/snapcore/snapd-desktop-integration/blob/d1cf830cdff7359a3926bb8a72e736c225adc0e4/src/main.c#L56-L59

We should be able to see the error by running:

    journalctl --user --unit snap.snapd-desktop-integration.snapd-desktop-integration.service

I think the reason we didn't include the error message in the UI was that it wasn't clear it was a particularly user-friendly message.

**Comment by jhenstridge** [comment]
When clicking on a notification in the tray, it will send a signal for the action named "default". So if we renamed our our "yes" action to "default", I think it would be called when clicking on the notification in the tray. This wouldn't require changing the text visible to the user: just the ID of the action.

**Comment by sergio-costas** [comment]
Mmm... but what if the user just clicks it by accident? Maybe it would be better to make the "default" action to show a popup with the two options... What do you think?

**Comment by sergio-costas** [comment]
It's not enough to rename 'yes' action to 'default', because the default action isn't shown in the notification. I created a patch...

**Comment by sergio-costas** [comment]
Ok, sent two patches:

- one installs the snap if the user clicks on the notification when it is "stored": https://github.com/snapcore/snapd-desktop-integration/pull/36
- another shows a message "cancelled by the user." if the installation was cancelled by the user, and also allows to easily add more error messages if required: https://github.com/snapcore/snapd-desktop-integration/pull/37
