### ISSUE TITLE
if DISPLAY is unset, exit quietly with exit code 0

### ISSUE THREAD

**Issue by jdchristensen** [snapcore/snapd-desktop-integration#14]
My logs contain a lot of repeats of the following:
```
Jun 27 08:59:17 jdc snapd-desktop-i[921249]: cannot open display:
Jun 27 08:59:17 jdc systemd[921239]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Main process exited, code=exited, status=1/FAILURE
Jun 27 08:59:17 jdc systemd[921239]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Failed with result 'exit-code'.
Jun 27 08:59:18 jdc systemd[921239]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled restart job, restart counter is at 1.
```
When DISPLAY is not set, maybe snapd-desktop-integration should just silently exit (fixing the first line) and have a zero exit code (fixing the remaining lines and the 4 repeats of the above sequence)?

**Comment by sergio-costas** [comment]
Mmm... but are you manually unsetting DISPLAY?

**Comment by jdchristensen** [comment]
No, I am not manually unsetting DISPLAY.  The error happens when a user connects via ssh, in which case DISPLAY is not set.
