### ISSUE TITLE
Snap related error in dmesg, snapd-desktop-i[1403]: segfault at 0, error 4 in libglib-2.0

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [snapcore/snapd-desktop-integration#15]
I'm using Ubuntu mate 22.04 and default snap app of Firefox and my Bluetooth is turned off and following errors (they were in red colour in terminal) came up after using dmesg command:

`Bluetooth:` hci0: unexpected event for opcode 0x0000

`snapd-desktop-i[1403]:` segfault at 0 ip 00007fe679ea8364 sp 00007ffc1f2e83f8 error 4 in `libglib-2.0.so.0.6400.6[7fe679e7e000+9a000]

**Comment by iamforgettable** [comment]
I'm seeing similar things under plain Ubuntu 22.04:

`[   36.804978] snapd-desktop-i[3186]: segfault at 0 ip 00007f1b5d74e364 sp 00007ffd3816a668 error 4 in libglib-2.0.so.0.6400.6[7f1b5d724000+9a000]
[   36.804989] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 c3 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89`

**Comment by robert-ancell** [comment]
This going to be almost impossible to diagnose without a repeatable test case or a stack trace. Note that there doesn't seem to be any information in errors.ubuntu.com because this is a snap and not a .deb?

**Comment by iamforgettable** [comment]
FWIW this seems to only happen on my machine on each boot. Note the 36-39 second from boot prefix:

```
[   36.253331] snapd-desktop-i[2958]: segfault at 0 ip 00007f6de0c0a364 sp 00007ffe7a5a68d8 error 4 in libglib-2.0.so.0.6400.6[7f6de0be0000+9a000]

[   36.804978] snapd-desktop-i[3186]: segfault at 0 ip 00007f1b5d74e364 sp 00007ffd3816a668 error 4 in libglib-2.0.so.0.6400.6[7f1b5d724000+9a000]

[   37.591993] snapd-desktop-i[3288]: segfault at 0 ip 00007fa164bba364 sp 00007ffc7d86dbc8 error 4 in libglib-2.0.so.0.6400.6[7fa164b90000+9a000]

[   38.233296] snapd-desktop-i[3370]: segfault at 0 ip 00007f18c6bf9364 sp 00007ffd58eef068 error 4 in libglib-2.0.so.0.6400.6[7f18c6bcf000+9a000]

[   38.808052] snapd-desktop-i[3516]: segfault at 0 ip 00007f16b73ac364 sp 00007ffe7b23b418 error 4 in libglib-2.0.so.0.6400.6[7f16b7382000+9a000]

[   39.691261] snapd-desktop-i[3769]: segfault at 0 ip 00007fd394147364 sp 00007ffda0eea4f8 error 4 in libglib-2.0.so.0.6400.6[7fd39411d000+9a000]
```

Probably not going to make getting a reproducible test case any easier...

**Comment by tejohnso** [comment]
[   37.743173] snapd-desktop-i[1782]: segfault at 0 ip 00007f271a638364 sp 00007ffe5ac64478 error 4 in libglib-2.0.so.0.6400.6[7f271a60e000+9a000]

[   37.743188] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 c3 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa
<0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89

Preceded by
[   36.698480] watchdog: BUG: soft lockup - CPU#2 stuck for 31s! [swapper/2:0]

[   36.698493] Modules linked in: vboxvideo(OE) drm_ttm_helper snd_hda_codec_idt snd_hda_codec_generic ledtrig_audio snd_hda_intel snd_intel_dspcfg snd_intel_sdw_acpi snd_hda_codec intel_rapl_msr snd_hda_core snd_hwdep intel_rapl_common nls_iso8859_1 snd_pcm snd_seq_midi snd_seq_midi_event snd_rawmidi snd_seq crct10dif_pclmul ghash_clmulni_intel aesni_intel crypto_simd cryptd snd_seq_device joydev input_leds serio_raw snd_timer snd vboxguest(OE) soundcore mac_hid sch_fq_codel vmwgfx ttm drm_kms_helper cec rc_core fb_sys_fops syscopyarea sysfillrect sysimgblt ipmi_devintf ipmi_msghandler msr parport_pc ppdev lp ramoops parport reed_solomon mtd pstore_blk efi_pstore drm pstore_zone ip_tables x_tables autofs4 hid_generic usbhid
hid xhci_pci ahci crc32_pclmul e1000 libahci psmouse i2c_piix4 xhci_pci_renesas pata_acpi video
[   36.698565] sched: RT throttling activated
[   36.698567] CPU: 2 PID: 0 Comm: swapper/2 Tainted: G           OE     5.15.0-46-generic #49-Ubuntu
[   36.698570] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[   36.698572] RIP: 0010:native_safe_halt+0xb/0x10
[   36.698584] Code: 2d ff 5b 41 5c 41 5d 5d c3 cc cc cc cc 4c 89 ee 48 c7 c7 a0 43 85 b0 e8 c3 98 8d ff eb ca cc eb 07 0f 00 2d 69 37 46 00 fb f4
<c3> cc cc cc cc eb 07 0f 00 2d 59 37 46 00 f4 c3 cc cc cc cc cc 0f
[   36.698585] RSP: 0018:ffffad808009be78 EFLAGS: 00000202
[   36.698587] RAX: ffffffffaf7aa5b0 RBX: ffff941e80308000 RCX: 0000000000000000
[   36.698589] RDX: 0000000000006b31 RSI: ffffad808009be40 RDI: 0000000000006b32
[   36.698589] RBP: ffffad808009be80 R08: 0000000000000001 R09: 0000000000000001
[   36.698590] R10: 0000000000000000 R11: 0000000000000000 R12: 0000000000000000
[   36.698591] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[   36.698592] FS:  0000000000000000(0000) GS:ffff941f97280000(0000) knlGS:0000000000000000
[   36.698593] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   36.698594] CR2: 00007f8c81282008 CR3: 0000000144fea000 CR4: 00000000000506e0
[   36.698596] Call Trace:
[   36.698599]  <TASK>
[   36.698600]  ? default_idle+0xe/0x20
[   36.698606]  arch_cpu_idle+0x15/0x20
[   36.698611]  default_idle_call+0x3e/0xd0
[   36.698612]  cpuidle_idle_call+0x179/0x1e0
[   36.698616]  do_idle+0x83/0xf0
[   36.698617]  cpu_startup_entry+0x20/0x30
[   36.698618]  start_secondary+0x12a/0x180
[   36.698621]  secondary_startup_64_no_verify+0xc2/0xcb
[   36.698625]  </TASK>

**Comment by niketpathak** [comment]
Hello, I'm seeing similar errors. My system freezes completely requiring a hard reboot! Everything including the mouse freezes! 
This happens pretty randomnly.

```
   17.729553] usb 1-13: reset high-speed USB device number 5 using xhci_hcd
[   18.084397] snapd-desktop-i[2207]: segfault at 0 ip 00007fab294283d4 sp 00007ffc82a0c158 error 4 in libglib-2.0.so.0.6400.6[7fab293fe000+9a000]
[   18.084404] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   18.522838] audit: type=1400 audit(1663742658.519:89): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2426 comm="snap-confine" capability=12  capname="net_admin"
[   18.522841] audit: type=1400 audit(1663742658.519:90): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2426 comm="snap-confine" capability=38  capname="perfmon"
[   18.602972] snapd-desktop-i[2426]: segfault at 0 ip 00007f5d7e2353d4 sp 00007fff071b5aa8 error 4 in libglib-2.0.so.0.6400.6[7f5d7e20b000+9a000]

```

**Comment by JonasV328** [comment]
I have the same error. It seems to appear directly on boot. Ubuntu Mate 22.04, only a-few-days-old fresh install. Ubuntu offers to send a crash report, but if I agree, nothing happens. If I can help with any further info, please let me know.

```
[   12.384089] audit: type=1400 audit(1664200380.267:58): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=1604 comm="snap-confine" capability=12  capname="net_admin"
[   12.384111] audit: type=1400 audit(1664200380.267:59): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=1604 comm="snap-confine" capability=38  capname="perfmon"
[   13.373048] snapd-desktop-i[1604]: segfault at 0 ip 00007ffb3e7f03d4 sp 00007ffe019fbe68 error 4 in libglib-2.0.so.0.6400.6[7ffb3e7c6000+9a000]
[   13.373071] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   13.885702] audit: type=1400 audit(1664200381.767:60): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=1732 comm="snap-confine" capability=12  capname="net_admin"
[   13.885713] audit: type=1400 audit(1664200381.767:61): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=1732 comm="snap-confine" capability=38  capname="perfmon"

```

**Comment by sergio-costas** [comment]
Can you install "valgrind", then in a terminal launch

    valgrind /snap/snapd-desktop-integration/current/bin/snapd-desktop-integration

and "make it fail"? (disabling the bluetooth, or waiting...) and paste here the output.

**Comment by golivag** [comment]
==4805== Invalid read of size 1
==4805==    at 0x512D414: g_str_hash (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x512E179: g_hash_table_lookup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x10B076: check_themes_cb (main.c:142)
==4805==    by 0x524B676: ??? (in /usr/lib/x86_64-linux-gnu/libsnapd-glib.so.1.0.0)
==4805==    by 0x514AC23: g_main_context_dispatch (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x519F6F7: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x514A292: g_main_loop_run (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x10B799: main (main.c:283)
==4805==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==4805== 
==4805== 
==4805== Process terminating with default action of signal 11 (SIGSEGV)
==4805==  Access not within mapped region at address 0x0
==4805==    at 0x512D414: g_str_hash (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x512E179: g_hash_table_lookup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x10B076: check_themes_cb (main.c:142)
==4805==    by 0x524B676: ??? (in /usr/lib/x86_64-linux-gnu/libsnapd-glib.so.1.0.0)
==4805==    by 0x514AC23: g_main_context_dispatch (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x519F6F7: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x514A292: g_main_loop_run (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1)
==4805==    by 0x10B799: main (main.c:283)
==4805==  If you believe this happened as a result of a stack
==4805==  overflow in your program's main thread (unlikely but
==4805==  possible), you can try to increase the size of the
==4805==  main thread stack using the --main-stacksize= flag.
==4805==  The main thread stack size used in this run was 8388608.
==4805== 
==4805== HEAP SUMMARY:
==4805==     in use at exit: 2,134,202 bytes in 18,913 blocks
==4805==   total heap usage: 266,100 allocs, 247,187 frees, 19,903,949 bytes allocated
==4805== 
==4805== LEAK SUMMARY:
==4805==    definitely lost: 48 bytes in 1 blocks
==4805==    indirectly lost: 1,689 bytes in 44 blocks
==4805==      possibly lost: 3,040 bytes in 3 blocks
==4805==    still reachable: 2,051,153 bytes in 18,150 blocks
==4805==         suppressed: 0 bytes in 0 blocks
==4805== Rerun with --leak-check=full to see details of leaked memory
==4805== 
==4805== For lists of detected and suppressed errors, rerun with: -s
==4805== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

**Comment by sergio-costas** [comment]
Thanks!!!! I'll check it right now.

**Comment by sergio-costas** [comment]
@golivag Also, can you install "libglib2.0-0-dbgsym" and repeat the valgrind, please?

**Comment by golivag** [comment]
==6312== Memcheck, a memory error detector
==6312== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==6312== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==6312== Command: /snap/snapd-desktop-integration/current/bin/snapd-desktop-integration
==6312== 
** Message: 15:36:49.158: New theme: gtk=Yaru icon=Yaru cursor=(null), sound=Yaru
==6312== Invalid read of size 1
==6312==    at 0x512E414: g_str_hash (ghash.c:2360)
==6312==    by 0x512F179: UnknownInlinedFun (ghash.c:472)
==6312==    by 0x512F179: g_hash_table_lookup (ghash.c:1538)
==6312==    by 0x10B076: check_themes_cb (main.c:142)
==6312==    by 0x524C676: respond_cb (snapd-request.c:84)
==6312==    by 0x514BC23: UnknownInlinedFun (gmain.c:3417)
==6312==    by 0x514BC23: g_main_context_dispatch (gmain.c:4135)
==6312==    by 0x51A06F7: g_main_context_iterate.constprop.0 (gmain.c:4211)
==6312==    by 0x514B292: g_main_loop_run (gmain.c:4411)
==6312==    by 0x10B799: main (main.c:283)
==6312==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==6312== 
==6312== 
==6312== Process terminating with default action of signal 11 (SIGSEGV)
==6312==  Access not within mapped region at address 0x0
==6312==    at 0x512E414: g_str_hash (ghash.c:2360)
==6312==    by 0x512F179: UnknownInlinedFun (ghash.c:472)
==6312==    by 0x512F179: g_hash_table_lookup (ghash.c:1538)
==6312==    by 0x10B076: check_themes_cb (main.c:142)
==6312==    by 0x524C676: respond_cb (snapd-request.c:84)
==6312==    by 0x514BC23: UnknownInlinedFun (gmain.c:3417)
==6312==    by 0x514BC23: g_main_context_dispatch (gmain.c:4135)
==6312==    by 0x51A06F7: g_main_context_iterate.constprop.0 (gmain.c:4211)
==6312==    by 0x514B292: g_main_loop_run (gmain.c:4411)
==6312==    by 0x10B799: main (main.c:283)
==6312==  If you believe this happened as a result of a stack
==6312==  overflow in your program's main thread (unlikely but
==6312==  possible), you can try to increase the size of the
==6312==  main thread stack using the --main-stacksize= flag.
==6312==  The main thread stack size used in this run was 8388608.
==6312== 
==6312== HEAP SUMMARY:
==6312==     in use at exit: 2,134,512 bytes in 18,917 blocks
==6312==   total heap usage: 266,139 allocs, 247,222 frees, 19,906,451 bytes allocated
==6312== 
==6312== LEAK SUMMARY:
==6312==    definitely lost: 48 bytes in 1 blocks
==6312==    indirectly lost: 1,689 bytes in 44 blocks
==6312==      possibly lost: 3,040 bytes in 3 blocks
==6312==    still reachable: 2,051,463 bytes in 18,154 blocks
==6312==         suppressed: 0 bytes in 0 blocks
==6312== Rerun with --leak-check=full to see details of leaked memory
==6312== 
==6312== For lists of detected and suppressed errors, rerun with: -s
==6312== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

**Comment by golivag** [comment]
It happens on i3 session, not on a regular ubuntu session

**Comment by sergio-costas** [comment]
Ooook... the problem seems to be that CURSOR is NULL...

Thanks! I think that now I will be able to fix it.
