### ISSUE TITLE
snapd-desktop-i segfaulting crashing and restarting at system boot

### ISSUE THREAD

**Issue by MattWeatherford** [snapcore/snapd-desktop-integration#19]
Hi Folks,

I see snapd-desktop-i segfaulting crashing and restarting at system boot time on a physical machine running Ubuntu 22.04 AMD64 w/Dell Server hardware.  The 22.04 System is largely up to date

Data / info / logs/ crash msgs below:

# grep snapd-desktop /var/log/syslog
Sep 26 08:17:57 ika systemd[3928]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 08:17:57 ika systemd[3928]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Failed with result 'exit-code'.
Sep 26 08:17:58 ika systemd[3928]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled restart job, restart counter is at 5.
Sep 26 08:17:58 ika systemd[3928]: Stopped Service for snap application snapd-desktop-integration.snapd-desktop-integration.
Sep 26 08:17:58 ika systemd[3928]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Start request repeated too quickly.
Sep 26 08:17:58 ika systemd[3928]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Failed with result 'exit-code'.
Sep 26 08:17:58 ika systemd[3928]: Failed to start Service for snap application snapd-desktop-integration.snapd-desktop-integration.
root@ika:/homes# 

root@ika:/homes# snap list
Name                            Version             Rev    Tracking         Publisher     Notes
bare                            1.0                 5      latest/stable    canonical✓    base
certbot                         1.30.0              2344   latest/stable    certbot-eff✓  classic
core20                          20220826            1623   latest/stable    canonical✓    base
firefox                         105.0.1-1           1883   latest/stable/…  mozilla✓      -
gnome-3-38-2004                 0+git.891e5bc       115    latest/stable/…  canonical✓    -
gtk-common-themes               0.1-81-g442e511     1535   latest/stable/…  canonical✓    -
hunspell-dictionaries-1-7-2004  1.7-20.04+pkg-6fd6  2      latest/stable    brlin         -
snap-store                      41.3-64-g512c0ff    599    latest/stable/…  canonical✓    -
snapd                           2.57.1              16778  latest/stable    canonical✓    snapd
snapd-desktop-integration       0.1                 14     latest/stable/…  canonical✓    -
root@ika:/homes# snap info snapd-desktop-integration
name:      snapd-desktop-integration
summary:   Desktop Integration for snapd
publisher: Canonical✓
store-url: https://snapcraft.io/snapd-desktop-integration
contact:   https://github.com/snapcore/snapd-desktop-integration
license:   unset
description: |
  Provides a user session daemon used to provide a bridge between the user's session and snapd. 
  Used for things like automatic theme installation.
services:
  snapd-desktop-integration: simple, enabled, inactive
snap-id:      IrwRHakqtzhFRHJOOPxKVPU0Kk7Erhcu
tracking:     latest/stable/ubuntu-22.04
refresh-date: 29 days ago, at 15:19 PDT
channels:
  latest/stable:    0.1 2022-06-02 (14) 290kB -
  latest/candidate: 0.1 2022-09-23 (19) 294kB -
  latest/beta:      ↑                         
  latest/edge:      0.1 2022-09-23 (19) 294kB -
installed:          0.1            (14) 290kB -
root@ika:/homes# 

CRASH data in DMESG output:

[   26.208860] snapd-desktop-i[2496]: segfault at 0 ip 00007fdbe17f13d4 sp 00007ffeeb625618 error 4 in libglib-2.0.so.0.6400.6[7fdbe17c7000+9a000]
[   26.208875] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   26.208880] potentially unexpected fatal signal 11.
[   26.208882] CPU: 31 PID: 2496 Comm: snapd-desktop-i Tainted: G          I       5.15.0-48-generic #54-Ubuntu
[   26.208885] Hardware name: Dell Inc. PowerEdge R640/0W23H8, BIOS 2.15.1 06/15/2022
[   26.208887] RIP: 0033:0x7fdbe17f13d4
[   26.208892] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   26.208894] RSP: 002b:00007ffeeb625618 EFLAGS: 00010202
[   26.208896] RAX: 0000559a542f1180 RBX: 0000559a542f1180 RCX: 000000000000ffd0
[   26.208898] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[   26.208899] RBP: 0000000000000002 R08: 0000000000000000 R09: 0000559a542334c0
[   26.208901] R10: fffffffffffff60f R11: 00007fdbe17efca0 R12: 0000559a52406f6b
[   26.208902] R13: 0000000000000000 R14: 00007fdbe18e7960 R15: 0000559a541de770
[   26.208904] FS:  00007fdbdd820ac0 GS:  0000000000000000
[   26.833286] audit: type=1400 audit(1664205440.019:69): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2670 comm="snap-confine" capability=12  capname="net_admin"
[   26.833303] audit: type=1400 audit(1664205440.019:70): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2670 comm="snap-confine" capability=38  capname="perfmon"
[   27.117772] snapd-desktop-i[2670]: segfault at 0 ip 00007faa7022d3d4 sp 00007ffd2a8aaad8 error 4 in libglib-2.0.so.0.6400.6[7faa70203000+9a000]
[   27.117806] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   27.117825] potentially unexpected fatal signal 11.
[   27.117829] CPU: 38 PID: 2670 Comm: snapd-desktop-i Tainted: G          I       5.15.0-48-generic #54-Ubuntu
[   27.117839] Hardware name: Dell Inc. PowerEdge R640/0W23H8, BIOS 2.15.1 06/15/2022
[   27.117843] RIP: 0033:0x7faa7022d3d4
[   27.117896] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   27.117902] RSP: 002b:00007ffd2a8aaad8 EFLAGS: 00010202
[   27.117911] RAX: 00005639dd6cc980 RBX: 00005639dd6cc980 RCX: 000000000000ffd0
[   27.117918] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[   27.117924] RBP: 0000000000000002 R08: 0000000000000000 R09: 00005639dd60f750
[   27.117928] R10: fffffffffffff60f R11: 00007faa7022bca0 R12: 00005639dca55f6b
[   27.117933] R13: 0000000000000000 R14: 00007faa70323960 R15: 00005639dd5c9eb0
[   27.117938] FS:  00007faa6c25cac0 GS:  0000000000000000
[   27.668729] audit: type=1400 audit(1664205440.855:71): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2766 comm="snap-confine" capability=12  capname="net_admin"
[   27.668746] audit: type=1400 audit(1664205440.855:72): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2766 comm="snap-confine" capability=38  capname="perfmon"
[   27.961836] snapd-desktop-i[2766]: segfault at 0 ip 00007f78a368d3d4 sp 00007ffcd0a4f268 error 4 in libglib-2.0.so.0.6400.6[7f78a3663000+9a000]
[   27.961849] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   27.961856] potentially unexpected fatal signal 11.
[   27.961858] CPU: 35 PID: 2766 Comm: snapd-desktop-i Tainted: G          I       5.15.0-48-generic #54-Ubuntu
[   27.961861] Hardware name: Dell Inc. PowerEdge R640/0W23H8, BIOS 2.15.1 06/15/2022
[   27.961863] RIP: 0033:0x7f78a368d3d4
[   27.961868] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   27.961869] RSP: 002b:00007ffcd0a4f268 EFLAGS: 00010202
[   27.961872] RAX: 000055a45bf56580 RBX: 000055a45bf56580 RCX: 00000000ffffffd0
[   27.961874] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[   27.961875] RBP: 0000000000000002 R08: 0000000000000000 R09: 000055a45be98300
[   27.961877] R10: fffffffffffff60f R11: 00007f78a368bca0 R12: 000055a45ba6cf6b
[   27.961878] R13: 0000000000000000 R14: 00007f78a3783960 R15: 000055a45be530b0
[   27.961880] FS:  00007f789f6bcac0 GS:  0000000000000000
[   28.506248] audit: type=1400 audit(1664205441.695:73): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2944 comm="snap-confine" capability=12  capname="net_admin"
[   28.506270] audit: type=1400 audit(1664205441.695:74): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=2944 comm="snap-confine" capability=38  capname="perfmon"
[   28.784368] snapd-desktop-i[2944]: segfault at 0 ip 00007f581eff93d4 sp 00007ffca442f2e8 error 4 in libglib-2.0.so.0.6400.6[7f581efcf000+9a000]
[   28.784401] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   28.784419] potentially unexpected fatal signal 11.
[   28.784424] CPU: 38 PID: 2944 Comm: snapd-desktop-i Tainted: G          I       5.15.0-48-generic #54-Ubuntu
[   28.784433] Hardware name: Dell Inc. PowerEdge R640/0W23H8, BIOS 2.15.1 06/15/2022
[   28.784437] RIP: 0033:0x7f581eff93d4
[   28.784446] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   28.784451] RSP: 002b:00007ffca442f2e8 EFLAGS: 00010202
[   28.784459] RAX: 0000560573cc5980 RBX: 0000560573cc5980 RCX: 00000000ffffffd0
[   28.784464] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[   28.784468] RBP: 0000000000000002 R08: 0000000000000000 R09: 0000560573c07b30
[   28.784472] R10: fffffffffffff60f R11: 00007f581eff7ca0 R12: 0000560572d16f6b
[   28.784477] R13: 0000000000000000 R14: 00007f581f0ef960 R15: 0000560573bcb620
[   28.784482] FS:  00007f581b028ac0 GS:  0000000000000000
[   28.796853] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[   29.180454] audit: type=1400 audit(1664205442.367:75): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=3093 comm="snap-confine" capability=12  capname="net_admin"
[   29.180472] audit: type=1400 audit(1664205442.367:76): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=3093 comm="snap-confine" capability=38  capname="perfmon"
[   29.493896] snapd-desktop-i[3093]: segfault at 0 ip 00007f03d020f3d4 sp 00007ffdcf3f87c8 error 4 in libglib-2.0.so.0.6400.6[7f03d01e5000+9a000]
[   29.493928] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   29.493947] potentially unexpected fatal signal 11.
[   29.493951] CPU: 8 PID: 3093 Comm: snapd-desktop-i Tainted: G          I       5.15.0-48-generic #54-Ubuntu
[   29.493961] Hardware name: Dell Inc. PowerEdge R640/0W23H8, BIOS 2.15.1 06/15/2022
[   29.493965] RIP: 0033:0x7f03d020f3d4
[   29.493973] Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 53 70 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
[   29.493979] RSP: 002b:00007ffdcf3f87c8 EFLAGS: 00010202
[   29.493987] RAX: 0000556ffead8580 RBX: 0000556ffead8580 RCX: 000000000000ffd0
[   29.493992] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[   29.493996] RBP: 0000000000000002 R08: 0000000000000000 R09: 0000556ffea1b2c0
[   29.494001] R10: fffffffffffff60f R11: 00007f03d020dca0 R12: 0000556ffd492f6b
[   29.494006] R13: 0000000000000000 R14: 00007f03d0305960 R15: 0000556ffe9dea00
[   29.494010] FS:  00007f03cc23eac0 GS:  0000000000000000
[   30.076844] rfkill: input handler disabled
[   62.742813] audit: type=1400 audit(1664205476.111:77): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=4115 comm="snap-confine" capability=12  capname="net_admin"
[   62.742830] audit: type=1400 audit(1664205476.111:78): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=4115 comm="snap-confine" capability=38  capname="perfmon"
[   63.250693] audit: type=1400 audit(1664205476.619:79): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=4180 comm="snap-confine" capability=12  capname="net_admin"
[   63.250710] audit: type=1400 audit(1664205476.619:80): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=4180 comm="snap-confine" capability=38  capname="perfmon"
[   64.248184] audit: type=1400 audit(1664205477.615:81): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=4294 comm="snap-confine" capability=12  capname="net_admin"
[   64.248201] audit: type=1400 audit(1664205477.615:82): apparmor="DENIED" operation="capable" profile="/snap/snapd/16778/usr/lib/snapd/snap-confine" pid=4294 comm="snap-confine" capability=38  capname="perfmon"
[  851.451902] FS-Cache: Loaded
[  851.497296] RPC: Registered named UNIX socket transport module.

Lastly, I see that we have some held packages that I will investigate. I suspect these are "apt phased updates"....
 
root@ika:/homes#  apt list --upgradable
Listing... Done
libnss-systemd/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
libpam-systemd/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
libspeechd2/jammy-updates 0.11.1-1ubuntu2 amd64 [upgradable from: 0.11.1-1ubuntu1]
libsystemd0/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
libudev1/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
python3-speechd/jammy-updates,jammy-updates 0.11.1-1ubuntu2 all [upgradable from: 0.11.1-1ubuntu1]
speech-dispatcher-audio-plugins/jammy-updates 0.11.1-1ubuntu2 amd64 [upgradable from: 0.11.1-1ubuntu1]
speech-dispatcher-espeak-ng/jammy-updates 0.11.1-1ubuntu2 amd64 [upgradable from: 0.11.1-1ubuntu1]
speech-dispatcher/jammy-updates 0.11.1-1ubuntu2 amd64 [upgradable from: 0.11.1-1ubuntu1]
systemd-oomd/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
systemd-sysv/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
systemd/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
udev/jammy-updates 249.11-0ubuntu3.6 amd64 [upgradable from: 249.11-0ubuntu3.4]
root@ika:/homes# 
root@ika:/homes# 
root@ika:/homes# 
root@ika:/homes# apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libnss-systemd libpam-systemd libspeechd2 libsystemd0 libudev1 python3-speechd speech-dispatcher speech-dispatcher-audio-plugins speech-dispatcher-espeak-ng systemd systemd-oomd systemd-sysv udev
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
root@ika:/homes# 

not sure if those are meant to fix this issue or not

Anyway, this isnt really affecting the usability of the system so please prioritize at will / as you see fit

**Comment by kenvandine** [comment]
Thanks for the report, I think this was already reported at issue #15
