### ISSUE TITLE
Getting access denied journal messages when downloading/installing missing themes

### ISSUE THREAD

**Issue by fossfreedom** [snapcore/snapd-desktop-integration#7]
Using a fresh (19th March) Ubuntu Budgie 22.04 daily fully installed in virtualbox

snap refresh snapd --edge
reboot
snap install snapd-desktop-integration --edge

A popup message appears asking whether to download - I said yes.  Two further popups appeared saying the install of the two missing snap themes failed.

![Screenshot from 2022-03-19 21-50-48](https://user-images.githubusercontent.com/996240/159139623-b4d0cacf-3994-44b7-83ae-346edb9a7fe4.png)

In Ubuntu Budgie, the two snaps being installed are:

https://github.com/UbuntuBudgie/gtk-theme-qogirbudgie-snap/blob/main/snap/snapcraft.yaml

https://github.com/UbuntuBudgie/gtk-theme-pocillo-snap/blob/main/snap/snapcraft.yaml

Any thoughts what needs tweaking to get stuff working?

**Comment by kenvandine** [comment]
@jhenstridge can you please look at this?

**Comment by kenvandine** [comment]
Yeah, it would be fine to add it.  It won't be fully functional until snapd
2.55 lands.

**Comment by kenvandine** [comment]
@jhenstridge any updates on this?

**Comment by flexiondotorg** [comment]
@kenvandine I observe the same issue in Ubuntu MATE 22.04 daily which has `snapd` 2.55.2+22.04 installed.

 - Switching themes to Yaru-MATE-dark or Yaru-MATE-light displays a notification prompting if you want to install missing snapped themes.
 - Select Yes.
 - Enter password.
 - Notification says "Failed"
 
![image](https://user-images.githubusercontent.com/304639/161422962-b0d3160f-e6ce-4238-894f-098225a684fe.png)
 
 - However, the [`gtk-theme-yaru-mate`](https://github.com/ubuntu-mate/gtk-theme-yaru-mate-snap) and [`icon-theme-yaru-mate`](https://github.com/ubuntu-mate/icon-theme-yaru-mate-snap) snaps are installed.

@fossfreedom The only workaround I've found is to seed the snapped themes/icons, which kind of defeats the point and doesn't help the situation where someone is switching to any other theme that does have a snap published.

**Comment by jhenstridge** [comment]
I've been working on a fix for this: in short, the request to install the themes is working, but the requests to get the async status of the install are failing. The snap is the first user of a technique to grant access to a subset of the snapd REST API (as opposed to the current system where `snapd-control` grants access to everything, so is very rarely granted), and I missed this part of the API.

The snapd side has been fixed and cherry picked into the 2.55 branch here: https://github.com/snapcore/snapd/pull/11450. I'm working on a corresponding update to snapd-glib to properly make use of it.
